
branches:
  only: 
    - master

addons:
  homebrew:
    brewfile: true

cache: bundler

install:
  - npm i -g nativescript@5.4
  - npm i -g appium@1.13.0

matrix:
  include:
    - stage: "UI Tests"
      os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "8"
      install:
        - npm install -g ios-deploy
        - npm i
      script: 
        - tns build ios
        - find platforms -name *.app | xargs npm run e2e -- --runType sim.iPhone6  --appPath #$IOS_PACKAGE

    - os: linux
      env:
        - BuildAndroid="28"
      language: android
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - travis_wait travis_retry tns build android
        - find platforms -name *.apk | xargs npm run e2e -- --runType android26  --appPath #$IOS_PACKAGE



android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
